# : 后面有空格
# configuration: 配置
server:
  port: 9092
myyml:
  string: hello, yml

# 连接数据库, 看application.properties file里面，spring.datasource重复写了三遍
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8mb4&useSSL=true
    name: root
    password: 12345678

# 三种格式的区别：没有引号，单引号，双引号， 在UserController里面，看打印的效果
# 单引号和无引号，不会换行，特殊字符，会自动转义. e.g. \n -> \\n
mystring: 你好\n世界
mystring2: '你好\n世界'

# 双引号会换行
mystring3: "你好\n世界"

# 双引号不会换行
mystring4: "你好\\n世界"

# object 对象的多行的写法, 写法1
student:
  id: 1
  name: 张三
  age: 18

# object 对象的单行的写法, 写法2:
student2: { id: 2,name: 李四,age: 19 }

#集合, 行内写法
dbtypes: {name: [ mysql, sqlserver, db2 ]}